version: '3'
services:
  ipfs-dameon:
    image: ipfs/go-ipfs:release
    volumes:
      - ./storage-ipfs:/data/ipfs
    command: 'daemon --migrate=true --enable-pubsub-experiment' 
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 128M
        reservations:
          cpus: '0.5'
          memory: 64M
networks:
  outside:
    external:
      name: "host"

