version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-ipfs
    volumes:
      - ./storage-ipfs:/data/ipfs
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 1G
        reservations:
          cpus: '1.00'
          memory: 512M
networks:
  outside:
    external:
      name: "host"

