version: '3'
services:
  ipfs-dameon:
    image: ipfs/js-ipfs
    volumes:
      - ./storage-ipfs:/root/.jsipfs
      - ./:/wc
    working_dir: "/wc"
    command: ./new-init-and-daemon.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
        reservations:
          cpus: '1.00'
          memory: 512M
networks:
  outside:
    external:
      name: "host"

