version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-ipfs-2
    volumes:
      - ./storage-ipfs:/root/.jsipfs
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
networks:
  outside:
    external:
      name: "host"
